import pysign__anki
import pysign__articles
import pysign__assets
import pysign__common
import pysign__config
import pysign__formatting
import pysign__globals
import pysign__http
import pysign__sentences
import pysign__variants
import pysign__videos
import pysign__wordlists
